In [213]:
import numpy as np

from SimAnn import accept

In [214]:
M = 2
K = 2
s = np.random.choice([-1,1], size=(M,K))

In [215]:
N = 4

In [216]:
# index is the matrix reporting the index of the K variables of the m-th clause
index = np.zeros((M,K), dtype = int)
for m in range(M):
    index[m] = np.random.choice(N, size=(K), replace=False)

    # Dictionary for keeping track of literals in clauses
    clauses = []
    for n in range(N):
        clauses.append([i for i, row in enumerate(index) if n in row])

In [217]:
s

array([[ 1, -1],
       [ 1, -1]])

In [218]:
index

array([[0, 3],
       [3, 1]])

In [219]:
clauses

[[0], [1], [], [0, 1]]

In [220]:
s

array([[ 1, -1],
       [ 1, -1]])

In [221]:
x = np.ones(N, dtype=int)

def init_config(x, N):
    N = N
    x[:] = np.random.choice([-1,1], size=(N))

init_config(x, N)

In [222]:
x

array([ 1,  1, -1,  1])

In [244]:
def cost(x,s, influenced_clauses = None):
    if influenced_clauses is None:
        x = x[index]
        s = s
    else:
        x = x[index[influenced_clauses]]
        s = s[influenced_clauses]

    clause_cost = np.prod((1 - x * s) / 2, axis=1)

    return clause_cost.sum()

In [225]:
def propose_move(N):
    N = N
    move = np.random.choice(N)
    return move

In [226]:
move = propose_move(N)

In [229]:
def accept_move(x, move):
    x[move] *= -1

In [235]:
def compute_delta_cost(x, move, clauses, s):

    initial_x = x.copy()
    influenced_clauses = clauses[move]
    initial_cost = cost(initial_x, s, influenced_clauses)

    new_x = accept_move(initial_x, move)
    new_cost = cost(new_x, s, influenced_clauses,)

    print(f'new x = {new_x}\n'
          f'influenced clauses = {influenced_clauses}\n'
          f'initial cost = {initial_cost}\n'
          f'new cost = {new_cost}')

    return new_cost - initial_cost

In [236]:
compute_delta_cost(x, move, clauses, s)

new x = [-1  1 -1  1]
influenced clauses = [0]
initial cost = 0.0
new cost = 1.0


1.0